### ISSUE TITLE
Sign assembly with strong name

### ISSUE THREAD

**Issue by andreny** [RamBase/RamBaseApiDotNetSdk#2]
Typically gives the following error when loading the dependency: _Could not load file or assembly 'RamBaseApiSdk, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required._

**Comment by luciwoof** [comment]
Fixed in commit 1beb0b56de684e561e09a6325345b3922bf7225f

A new version has also been uploaded to NuGet.
