### ISSUE TITLE
Error getting metadata object

### ISSUE THREAD

**Issue by andreny** [RamBase/RamBaseApiDotNetSdk#5]
Seems like the metadata object in the SDK is out of sync with what is received from the API, so the deserializing fails. Get's the following error message for these code lines:

```csharp
var api = new RamBaseApi(accessToken, defaultPath: baseUrl);
var metadata = await api.GetMetadataAsync(uri.PathAndQuery, ApiResourceVerb.GET).ConfigureAwait(false);
```

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Unexpected character encountered while parsing value: {. Path 'namedFilters[0].uncombinableWith', line 673, position 9.)
  Source=System.Private.CoreLib

...

Inner Exception 1:
JsonReaderException: Unexpected character encountered while parsing value: {. Path 'namedFilters[0].uncombinableWith', line 673, position 9.
```

**Comment by luciwoof** [comment]
Hi @andreny,

I'm not able to reproduce this. Do you have an example with a failing `uri.PathAndQuery`

Regards,
@bal2

**Comment by andreny** [comment]
I believe the error is that NamedFilters.UncombinableWith expects a list of strings, but the API returns a list of objects.
https://github.com/RamBase/RamBaseApiDotNetSdk/blob/209c0cc63251899305b716cf3ecf3baecd91704a/RamBaseApiSdk/Meta/NamedFilter.cs#L10

Test with the /sales/customers API-resource.
